name: Build and Push Docker Images to GHCR (Auto-Detect & Versioning)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Specify a custom version (e.g., 1.5). Leave empty for auto-increment."
        required: false
        default: ""

  push:
    branches:
      - main
    paths:
      - "**/**"  # Detects any changed paths

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensures we have at least one previous commit

      - name: Convert Repository Owner to Lowercase
        run: echo "OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Detect Changed Directories
        id: detect_dirs
        run: |
          # Check if there's at least one previous commit
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            # Extract top-level directories from changed files
            CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD -- | awk -F/ '{print $1}' | sort -u | uniq | grep -v '^\.' || true)
          else
            # If first commit, consider all existing top-level directories
            CHANGED_DIRS=$(ls -d */ | cut -f1 -d'/' | grep -v '^\.' || true)
          fi

          # Debug output
          echo "Changed directories: $CHANGED_DIRS"

          # Store as GitHub environment variable
          echo "CHANGED_DIRS=$(echo $CHANGED_DIRS | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: |
          mkdir -p ~/.docker
          echo '{ "credsStore": "pass" }' > ~/.docker/config.json
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Determine Version and Build/Push Docker Images
        run: |
          if [[ -z "${{ env.CHANGED_DIRS }}" ]]; then
            echo "No directories were modified. Skipping build."
            exit 0
          fi

          for dir in ${{ env.CHANGED_DIRS }}; do
            if [[ ! -d "$dir" ]]; then
              echo "Skipping non-directory: $dir"
              continue
            fi

            IMAGE_NAME=ghcr.io/${{ env.OWNER }}/$dir
            echo "Processing directory: $dir"

            # Define the GHCR API URL for the specific package
            PACKAGE_URL="https://api.github.com/orgs/pacificcommunity/packages/container/$dir/versions"
            echo "Fetching GHCR versions from: $PACKAGE_URL"

            # Fetch all versions from GHCR
            API_RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                $PACKAGE_URL)

            # Extract valid version tags while filtering out empty arrays and 'latest'
            VERSION_TAGS=$(echo "$API_RESPONSE" | jq -r '[.[].metadata.container.tags? // [] | .[]] | map(select(test("^v?[0-9]+\\.[0-9]+$") and . != "latest")) | sort | last')

            # If no valid version is found, start at 1.0
            if [[ -z "$VERSION_TAGS" || "$VERSION_TAGS" == "null" ]]; then
              echo "No valid versions found. Setting initial version to 1.0"
              NEW_VERSION="1.0"
            else
              # Remove 'v' prefix if present (e.g., "v1.0" → "1.0")
              CLEAN_VERSION=$(echo "$VERSION_TAGS" | sed 's/^v//')

              # Increment minor version (e.g., 1.0 → 1.1)
              NEW_VERSION=$(awk -F. '{print $1 "." $2+1}' <<< "$CLEAN_VERSION")
              echo "Latest version detected: $CLEAN_VERSION. Incrementing to: $NEW_VERSION"
            fi

            # Save version to GitHub environment
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
            echo "Final version to be used: $NEW_VERSION"

            # Build Docker Image
            echo "Building Docker image: v${NEW_VERSION}"
            docker build -t $IMAGE_NAME:v${NEW_VERSION} -t $IMAGE_NAME:latest $dir/

            # Push Docker Image
            echo "Pushing Docker image: $IMAGE_NAME"
            docker push $IMAGE_NAME:v${NEW_VERSION}
            docker push $IMAGE_NAME:latest
          done
