name: Build and Push Docker Images to GHCR (User-Specified or Auto-Increment Version)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Specify a custom version (e.g., 1.5). Leave empty for auto-increment."
        required: false
        default: ""

  push:
    branches:
      - main
    paths:
      - "skj-2025/**"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Convert Repository Owner to Lowercase
        run: echo "OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

            - name: Determine Version
        id: get_version
        run: |
          # Define the GHCR API URL
          PACKAGE_URL="https://api.github.com/orgs/${{ env.OWNER }}/packages/container/skj-2025/versions"
          echo "Checking latest version from: $PACKAGE_URL"

          # Fetch versions from GitHub API
          API_RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" $PACKAGE_URL)

          # Debug: Print API response
          echo "API Response: $API_RESPONSE"

          # If user specified a version, use it
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            NEW_VERSION="${{ github.event.inputs.version }}"
            echo "Using user-specified version: $NEW_VERSION"
          else
            # Extract all numeric versions from API response
            LATEST_VERSION=$(echo "$API_RESPONSE" | jq -r '[.[].name] | map(select(test("^[0-9]+\\.[0-9]+$"))) | max')

            # If no valid version is found, start at 1.0
            if [[ -z "$LATEST_VERSION" || "$LATEST_VERSION" == "null" ]]; then
              echo "No valid versions found. Setting initial version to 1.0"
              NEW_VERSION="1.0"
            else
              # Increment minor version (e.g., 1.0 → 1.1)
              NEW_VERSION=$(awk -F. '{print $1 "." $2+1}' <<< "$LATEST_VERSION")
              echo "Latest version detected: $LATEST_VERSION. Incrementing to: $NEW_VERSION"
            fi
          fi

          # Save version in GitHub environment
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Final version to be used: $NEW_VERSION"

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ env.OWNER }}/skj-2025
          echo "Building Docker image with version: v${{ env.NEW_VERSION }}"

          # Docker Build & Push
          docker build -t $IMAGE_NAME:v${{ env.NEW_VERSION }} -t $IMAGE_NAME:latest skj-2025/
          docker push $IMAGE_NAME:v${{ env.NEW_VERSION }}
          docker push $IMAGE_NAME:latest

