name: Build and Push Docker Images to GHCR (Auto Versioning)

on:
  push:
    branches:
      - main
    paths:
      - "skj-2025/**"
      
permissions:
  contents: read
  packages: write      

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Convert Repository Owner to Lowercase
        run: echo "OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin


      - name: Get Latest Version
        id: get_version
        run: |
          PACKAGE_URL="https://api.github.com/orgs/${{ env.OWNER }}/packages/container/skj-2025/versions"
          LATEST_VERSION=$(curl -s -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" $PACKAGE_URL | jq -r '.[0].name' | sed 's/v//')
          if [[ "$LATEST_VERSION" == "null" ]]; then
            NEW_VERSION="1.0"
          else
            NEW_VERSION=$(awk -F. '{print $1 "." $2+1}' <<< "$LATEST_VERSION")
          fi
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ env.OWNER }}/skj-2025
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:v${{ env.NEW_VERSION }} skj-2025/
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:v${{ env.NEW_VERSION }}

      - name: Make GHCR Public
        run: |
          curl -X PATCH https://api.github.com/orgs/${{ env.OWNER }}/packages/container/skj-2025/visibility \
            -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"visibility":"public"}'