name: Build and Push Docker Images to GHCR (Public)

on:
  push:
    branches:
      - main
    paths:
      - "skj-2025/**"
#      - "yft-2025/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [skj-2025] 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}
          docker build -t $IMAGE_NAME:latest ${{ matrix.project }}
          docker push $IMAGE_NAME:latest